### ISSUE TITLE
[chore]: prompt the user to create a personal access token beforehand

### ISSUE THREAD

**Issue by SSmale** [madlabsinc/teachcode#23]
**Describe the bug**
The docs do not include the features that the application is requesting to use from GitHub or the steps needed to use the application CLI with 2FA enabled.

**Comment by SSmale** [comment]
[https://help.github.com/en/articles/accessing-github-using-two-factor-authentication#using-two-factor-authentication-with-the-command-line](the relevant GitHub Help page)

**Comment by jamesgeorge007** [comment]
We can prompt the user to create a personal access token and provide it instead while being prompted for the credentials. Feel free to shoot up a PR :+1:

**Comment by jamesgeorge007** [comment]
@SSmale any updates here?

**Comment by rishabhKalakoti** [comment]
I need a little clarification. Do we need to add this just to the docs or we should also add it when teach-code is initialized and personal access token is requested?

**Comment by jamesgeorge007** [comment]
Done in #48
