### ISSUE TITLE
Unable to init teachcode on Windows Platform

### ISSUE THREAD

**Issue by jamesjose03** [madlabsinc/teachcode#44]
**Describe the bug**
Unable to init teachcode in Windows.

**To Reproduce**

N/A
**Expected behavior**
Teachcode should have created the directory and start running.
**Screenshots**
![Screenshot (27)](https://user-images.githubusercontent.com/31133182/67879758-83052f80-fb63-11e9-9a82-179f896369ad.png)

**Environment Information**

OS: Windows 10
**Additional context**
N/A

**Comment by abhijithvijayan** [comment]
Assign to me

**Comment by jamesgeorge007** [comment]
Done in #46
