### ISSUE TITLE
Include JavaScript challenges

### ISSUE THREAD

**Issue by jamesgeorge007** [madlabsinc/teachcode#5]
As the next major update include challenges for JavaScript covering all the syntax part with strict emphasis for `Es6`.

**Comment by SSmale** [comment]
I would love to work on this. do you have any guidelines on the scope for the 30 steps?

**Comment by jamesgeorge007** [comment]
@SSmale thank you for showing interest :clap:
As of now we've almost 11 tasks tracked within the [js-tasks](https://github.com/madlabsinc/teachcode/tree/js-tasks) branch. Feel free to submit rest of the tasks following any of the beginner-friendly approach :+1:

**Comment by jamesgeorge007** [comment]
Also, make sure that you target `js-tasks` as your base branch while submitting PR's. After everything's done I'm gonna land them on `next` thereafter to `master` for the future release.

**Comment by jamesgeorge007** [comment]
@getamas feel free to pick up a portion that you would love to work upon :+1:
