### ISSUE TITLE
will it not be better to create a web-app using React or other frameworks over the CLI?

### ISSUE THREAD

**Issue by aldrin163** [madlabsinc/teachcode#65]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jamesgeorge007** [comment]
`Fear of the Terminal` is what prevents most beginners from their venture in learning how to code. `teachcode` was born of this realization. But it is still in the infancy state and requires a collaborative effort to get there.
