### ISSUE TITLE
No "initital key" to grab exists!

### ISSUE THREAD

**Issue by cl0wnm3at** [madlabsinc/teachcode#66]
**Describe the bug**
After typng in `cd teachcode-solutions` and being at the CL prompt in that subdir, there is no `<key>` of any kind to fetch with the `teachcode fetchtask <key>` command.

Furthermore, when I type `teachcode showcommands` , I get the following error message:
`Config file doesn't exist!`

**To Reproduce**
I am able to reproduce this behavior again and again, just by following the instructions.

**Expected behavior**
I expected to be presented with a key (though I have no idea what it would be....an integer like "1", maybe?

**Screenshots**

**Environment Information**
I am in using Gnome on Manjaro Linux

**Additional context**

**Comment by jamesgeorge007** [comment]
@cl0wnm3at it should be like this:-

1. Type in `teachcode init`
2. Choose your learning track and provide associated information (GitHub Auth).
3. You'll be greeted with a message asking you to navigate to the `teachcode-solutions` directory and type in `teachcode fetchtask <key>`
4. Hence, type in `cd teachcode-solutions`
5. If you lost the key, type in `teachcode showkeys` and grab the very first key.
6. Solve the task and type in `teachcode submit`
7. Boom :tada:
