### ISSUE TITLE
Better explain the purpose behind creating a personal access token

### ISSUE THREAD

**Issue by Beamanator** [madlabsinc/teachcode#73]
**Describe the bug**
The only instructions for creating the access token are [here, on github](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line), but they aren't definitive. For example, step 7 under "creating a token" says `"Select the scopes, or permissions, you'd like to grant this token. To use your token to access repositories from the command line, select repo."` -> And there's an image of 9 checkboxes you can choose from (plus sub-checkboxes).

Additionally, to an outside observer (with very little experience in the realm of personal access tokens) I am a bit wary of creating something that seems to resemble a private key (which should be kept very private) and inserting it into a program I want to test out, for the sake of `"Resume Anytime - All completed tasks are pushed to a remote repository which makes it easier to track the user progress."` - Can you clarify the purpose of the personal access token and how it's safe (if it is) to enter into your program? :)

**To Reproduce**
`Open browser to read instructions?` -> `Yes`

**Expected behavior**
Show clearer steps somewhere for creating the token + clearly describe how it's not a risk to enter your "personal access token" into this software.

**Screenshots**
N/A (if my explanation above isn't clear, I can try to send screenshots)

**Environment Information**
N/A

**Additional context**
I am currently teaching some students how to code and I'd love if they could not be scared of the terminal, so I'm super interested in this project!

**Comment by jamesgeorge007** [comment]
@Beamanator thanks for raising your concern :clap: I'm sorry for your inconvenience. As you may have noticed the project is in it's early stage and a collaborative effort is required to get things done. 

Regarding your question, we make use of GitHub as a medium to track the user progress. Once the user successfully completes a task, the respective solution (file) is pushed to his remote repository. The user token being generated is required in-order to overcome the rate limit for consuming the GitHub API and I can assure you that there isn't any sort of issues arising with that.

Feel free to come up with your questions :)
