### ISSUE TITLE
teachcode fetchtask <key> doesn't create a new task

### ISSUE THREAD

**Issue by abhijithneilabraham** [madlabsinc/teachcode#78]
https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/

As shown above, the API authentication through query parameters have deprecated, the workaround for the same is given in the above link itself.

**To Reproduce**
```teachcode fetch <key>

**Expected behavior**
Personal access token won't be authenticated and is deprecated.



**Environment Information**
MacOS High Sierra

**Comment by jamesgeorge007** [comment]
Thanks for reporting.

This would do it:-

https://github.com/madlabsinc/teachcode/blob/ea1b46f91889b1cadb120806edebb12672fc4d37/src/utils/github.js#L95

```js
  const API_URL = `https://api.github.com/user/repos`;
  axios.defaults.headers.common['Authorization'] = `token ${userToken}`;
```

Feel free to shoot a PR.
