### ISSUE TITLE
Telegram Link is broken in the README.md

### ISSUE THREAD

**Issue by radnerus** [madlabsinc/teachcode#89]
**Link for the Telegram channel is broken**
<img width="421" alt="Screenshot 2020-08-07 at 12 37 24 AM" src="https://user-images.githubusercontent.com/21972848/89572098-4e3aad00-d846-11ea-9b78-2a70c3d44c7d.png">

**Comment by jamesgeorge007** [comment]
Hey @radnerus thanks for raising the issue, it should be https://t.me/teach_code. Feel free to shoot a PR 👍
