### ISSUE TITLE
migrate to GitHub Actions

### ISSUE THREAD

**Issue by stemount** [madlabsinc/teachcode#94]
## Do you want to request a feature or report a bug?
Request E2E and Linting as CI/CD

## What is the current behavior?
No automated CI/CD action occurs.

## What is the expected behavior?
As somebody opens a PR or commits against a branch, run the linting and E2E testing as per Issue #28 using GitHub action

As discussed over at https://www.youtube.com/watch?v=LyTUj6YQoBo

**Comment by jamesgeorge007** [comment]
Feel free to shoot a PR.
